name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2ed3703b69ce8eef0c29bf7eb603a5c3087a88c0c55d0d25ed3967e689090d0"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
