name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d95290cb816e05a0e75ada801bf3a1f738d3dd40e37dd7d87424feb536b86fc5"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
