name = "LunarFox"
author = "OrzMiku"
version = "1.1.11-hf+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35cf25e738ca434731aeeaa87bae6b1f800b2d415b3ee668c188ce1979a1d886"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
