name = "LunarFox"
author = "OrzMiku"
version = "1.3.3+mc1.21.1-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bf2ef6578ff0a1bc72df427a73789d64de700be8c02678349e1d49114954368"

[versions]
fabric = "0.18.6"
minecraft = "1.21.1"
