name = "LunarFox"
author = "OrzMiku"
version = "1.2.1+mc1.21.1_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce7de403573a63fd43b88e6d05505b7e05cf8bccceedb3dc75734ffe82bd5ec1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
