name = "LunarFox"
author = "OrzMiku"
version = "1.2.0+mc1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "841d229872bfabaab8db3dbd95389b33f05105eedf9be9f0313cc521b7a82178"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
