name = "LunarFox"
author = "OrzMiku"
version = "1.3.3+mc1.21.1-neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "644224107da1ac3128be818a92e9dfda9f9a27172ca5da36254703610300519d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
