name = "LunarFox"
author = "OrzMiku"
version = "1.0.1+mc1.21.1_neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e75a302fcab826cfd7b10b3ad7960aee1b898c10325a76559534144e8567945"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
