name = "LunarFox"
author = "OrzMiku"
version = "1.2.1-alpha.1+mc1.21.1_neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39c497ea370db86794d384221de4980052173e2dfea72651a99125667757ee80"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
