name = "LunarFox"
author = "OrzMiku"
version = "1.3.2+mc1.20.1-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7677c61b8e4971c436614d144f9ba157758c9d27d4c284a6ed4b4d85a8ad6aa9"

[versions]
fabric = "0.18.6"
minecraft = "1.20.1"
