name = "LunarFox"
author = "OrzMiku"
version = "1.3.3+mc1.21.11-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7270c17bb3f0fab7fff138d9af2faff65415dec163d7f21b144490537ffc05e4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
