name = "LunarFox"
author = "OrzMiku"
version = "1.3.2+mc1.21.11-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2961d0965317b93675652a03bfb4fc9cff21db74e04b9838c5c9683cc8395c21"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
