name = "LunarFox"
author = "OrzMiku"
version = "0.1.0-alpha.2+mc26.1.2-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed00a17c2d6e6696af209dc18e4c314c2d7c10cb836807834c03225f2f4a5dea"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
