name = "LunarFox"
author = "OrzMiku"
version = "1.2.1-alpha.3+mc1.21.10_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4e56d731524e4073b62e62b224833f2a7a2266d07d21864fad6f8ebbd555e85"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
