name = "LunarFox"
author = "OrzMiku"
version = "1.2.1-alpha.2+mc1.21.10_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21507d90aab7fd8087b3d6b943a6cb8e5187f6f2067c4f7c2df45170064291cd"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
