name = "LunarFox"
author = "OrzMiku"
version = "1.2.1-alpha.2+mc1.21.10_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e05f0a7608e84af437fcbc410b18930bc84ccd3e039c7e52c1ea2dc1616347e1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
