name = "LunarFox"
author = "OrzMiku"
version = "1.3.2+mc1.20.1-forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f60ea36316df71f6fe8a5b1a4d782c47ea0d813989dfbbb0eb90188ddfd6677"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
