name = "LunarFox"
author = "OrzMiku"
version = "1.1.11-hf+mc1.21.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7225f1b415b85bbb0b2025cafba9d5573bfa01b5b54ea1a915e4f1ddb18ca48"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
