name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.21.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f47eca017ba0cc0e85c6e0a0d9b6e5e2c6f62c39dbc1159da43af49e9270a6c8"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
