name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.21.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa00f4d098a8df45f52face7af93ee1e3c87395e09a5d3ce89602761aa07da6d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
