name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cc74a0e408219b6743837a846d890eaaa3ed5d60580238de4b156ec5d0fc1d3"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
