name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0e4b13aae4dece191e343374b549eac644fc0cb64c071f23f35773ea3425eed"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
