name = "LunarFox"
author = "OrzMiku"
version = "1.1.11-hf+mc1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5e059b2b9bdf5aee436f78767277194ed84bdbb963df7eede67b3b91069bf37"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
