name = "LunarFox"
author = "OrzMiku"
version = "1.1.13+mc1.21.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f92a528a0113555e2fd197c0389eac294ee5224db0261aaccf8b61ebf87aa299"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
