name = "LunarFox"
author = "OrzMiku"
version = "1.2.0+mc1.21.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8b80d5999494cf7cb0216eac720cdadeac2de10d29ceb08df35d1544b91b0a5"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
