name = "LunarFox"
author = "OrzMiku"
version = "1.2.0+mc1.21.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "438ce28ecaa86f0abceac8ce50c6ff8ddcf5a1d6dda684d1547aa806f8a5f5e0"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
