name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.21.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c050cd359c70ebefab87bfd4fc4fd58298abe0ae9c327a314e049c5adec94099"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
