name = "LunarFox"
author = "OrzMiku"
version = "1.1.9-beta.2+mc1.21.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54f28d9c37acfa4df077cd21ce3da5ce5327996287c5e40ff020fcef9a3addc5"

[versions]
fabric = "0.16.14"
minecraft = "1.21.8"
