name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.21.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47030f64b844ce00e1671bd4eccdfa7593fc04d660225329ff34c672a3a83df2"

[versions]
fabric = "0.17.2"
minecraft = "1.21.7"
