name = "LunarFox"
author = "OrzMiku"
version = "1.1.11-hf+mc1.21.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edb8b4a2eb2137c476cd6e4a36c2191cc87c2c5f5b511414c856844ac588eb34"

[versions]
fabric = "0.17.2"
minecraft = "1.21.7"
