name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.21.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8d0fb9a187e6f940e9d2e80afc92c7794e91286bb2c98d9c365490133eb7fed"

[versions]
fabric = "0.17.2"
minecraft = "1.21.7"
