name = "LunarFox"
author = "OrzMiku"
version = "1.2.1-alpha.2+mc1.21.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b782f2ebdb2e18d2ebd2f52d043acef4d70e5479ace4076ff2451b39e3cc759"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
