name = "LunarFox"
author = "OrzMiku"
version = "1.2.1-alpha.1+mc1.21.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a63c6142a6ccd7b43cfe6c2f393a07bbb406ba6e610eb4a3c07e2d595ccd6a11"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
