name = "LunarFox"
author = "OrzMiku"
version = "1.2.1-alpha.2+mc1.21.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d86926f5ca572502cfd1e8d994b2fa49690c807dedf8bcb1c4c84e347ac086c2"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
