name = "LunarFox"
author = "OrzMiku"
version = "1.1.13+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea292014d26487311b40b844ad1ac870063515fa7f493fc63c096cb7c698fa3e"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
