name = "LunarFox"
author = "OrzMiku"
version = "1.2.0+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c7e82ebc2f9c6589be0db9a6f5ddf668ce608b902f4dd4d2fcf50ccdfac46d4"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
