name = "LunarFox"
author = "OrzMiku"
version = "1.2.0+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c5919d5ac1b7a4e77ca9624c67af98e5320cf009ba3876397d21b2a70a3bee4"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
