name = "LunarFox"
author = "OrzMiku"
version = "1.1.9+mc1.21.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf18ae6445517e9eb912a16986eb6f3b9a94f953f7fb9982a33b36c8b641d2b6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
