name = "LunarFox"
author = "OrzMiku"
version = "1.1.11-hf+mc1.21.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3acb6255160b77fa64c166286083dea29fca5f32d310dbca7b43c4d0c7d4ae14"

[versions]
fabric = "0.17.2"
minecraft = "1.21.6"
