name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9cec1e85ff7041706fd6918ea90888f3cc913f7468b4dfc8048ef137142c24a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
