name = "LunarFox"
author = "OrzMiku"
version = "1.1.12+mc1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99c4d9965a9f2e57c82c8c8ede8df16933ddf2f4ccef9d1656293584832165e1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
