name = "LunarFox"
author = "OrzMiku"
version = "1.1.11-hf+mc1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cb7aa08d639f13c8f161423a3431ffe186a1f5a2a47b87c3de9e6917e900380"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
