name = "LunarFox"
author = "OrzMiku"
version = "1.3.5-alpha.2+mc26.3-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d10b647f4c92e04d5b988a1c4825eca5abb4defa378baadd2122f3ffb74d649"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
